line: kodo
limit: 3
streamers:
  /root/blive/Videos/22222222/22222222*.mp4:
    copyright: 1
    source: https://live.bilibili.com/22222222
    tid: 138
    cover: 
    title: XXXXXX直播回放-%Y年%M月%d日%H点场
    desc_format_id: 0
    desc: your description
    dynamic: ""
    tag: XXX,XXXXXX
    dtime: ~